modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
credits="${mod_credits}" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

# Dependency
[[dependencies.${mod_id}]]
    modId="lionfishapi"
    mandatory=true
    versionRange="[2.4,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="playeranimator"
    mandatory=true
    versionRange="[${player_animator_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="curios"
    mandatory=true
    versionRange="[${curios_version},)"
    ordering="NONE"
    side="BOTH"